version: "3.7"

services:
  macksnow:
    build:
      context: ./src/macksnow/
      target: development
    image: twinkling-gecko/macksnow:development
    volumes:
      - ./.go/pkg:/go/pkg
      - ./src/macksnow:/go/src/macksnow:cached
    ports:
      - 4000:4000

  tangerine:
    build:
      context: ./src/tangerine/
      target: development
    image: twinkling-gecko/tangerine:development
    volumes:
      - ./src/tangerine:/usr/src/app:cached
    ports:
      - 3000:3000

  enigma:
    image: nginx:latest
    volumes:
      - ./src/enigma/default.conf:/etc/nginx/conf.d/default.conf:cached
    ports:
      - 80:80
