version: "3.7"

services:
  macksnow:
    build:
      context: ./src/macksnow/
      target: development
    image: twinkling-gecko/macksnow:development
    volumes:
      - ./.go/pkg:/go/pkg
      - ./src/macksnow:/go/src/macksnow:cached
    environment:
      # username:password@protocol(address)/dbname?param=value
      - DSN=giant:leopard@tcp(giant)/macksnow?parseTime=true
    depends_on:
      - giant
    ports:
      - 4000:4000

  tangerine:
    build:
      context: ./src/tangerine/
      target: development
    image: twinkling-gecko/tangerine:development
    volumes:
      - ./src/tangerine:/usr/src/app:cached
    ports:
      - 3000:3000

  enigma:
    image: nginx:latest
    volumes:
      - ./src/enigma/default.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - macksnow
      - tangerine
    ports:
      - 80:80

  giant:
    image: mysql:latest
    volumes:
      - ./.db:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=leopard
      - MYSQL_DATABASE=macksnow
      - MYSQL_USER=giant
      - MYSQL_PASSWORD=leopard
    ports:
      - 3306:3306
