version: "3"

services:
  macksnow:
    image: golang:latest
    working_dir: /go/src/macksnow
    volumes:
      - ./.go/pkg:/go/pkg
      - ./src/macksnow:/go/src/macksnow:cached
    ports:
      - 4000:4000
    command: go run main.go

  tangerine:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./src/tangerine:/usr/src/app:cached
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    command: yarn nuxt-ts dev

  enigma:
    image: nginx:latest
    volumes:
      - ./src/enigma/default.conf:/etc/nginx/conf.d/default.conf:cached
    ports:
      - 80:80
