definitions:
  router.errorResponse:
    properties:
      message:
        type: string
    type: object
  router.indexResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/router.item'
        type: array
    type: object
  router.item:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      summary:
        type: string
      updated_at:
        type: string
      uri:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/items:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.indexResponse'
      summary: Get itemslist
  /api/v1/items/{id}:
    get:
      parameters:
      - description: Item ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.item'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/router.errorResponse'
      summary: Get item info
swagger: "2.0"
